openapi: 3.0.0
info:
  title: Kearch meta search engine gateway API
  description: Kearch meta search engine gateway API
  version: 0.1.0
servers:
  - url: '{scheme}://{me_host}:{port}/v0/me/gateway'
    variables:
      scheme:
        enum:
          - http
          - https
        default: https
      me_host:
        default: localhost
      port:
        default: '32400'
paths:
  /add_a_summary:
    post:
      summary: Add a summary to meta server.
      requestBody:
        description: A summary of the specialist server.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Summary'
      responses:
        '200':
          description: An info about the specialist server of the added summary.
          content:
            application/json:
              schema:
                type: object
                properties:
                  sp_host:
                    type: string
                  engine_name:
                    type: string
  /add_a_conenction_request:
    post:
      summary: Add a connection request sent from specialist server to meta server.
      requestBody:
        description: A connection request.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConnectionRequestOnME'
      responses:
        '200':
          description: An info about the specialist server that requested the connection.
          content:
            application/json:
              schema:
                type: object
                properties:
                  sp_host:
                    type: string
  /delete_a_conenction_request:
    delete:
      summary: Delete a connection request sent from specialist server to this meta server.
      parameters:
        - in: query
          name: sp_host
          schema:
            type: string
          description: A specialist host name of the connection request to delete.
      responses:
        '200':
          description: An info about the specialist server that requested the connection.
          content:
            application/json:
              schema:
                type: object
                properties:
                  sp_host:
                    type: string
  /retrieve:
    get:
      summary: Retrieve search results.
      parameters:
        - in: query
          name: queries
          schema:
            type: string
          description: Space-separated query words
        - in: query
          name: max_urls
          schema:
            type: integer
          description: Max number of URLs to retrive from specialist servers
        - in: query
          name: sp_host
          schema:
            type: string
          description: A host name to retrieve results from.
      responses:
        '200':
          description: Search results.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Document'

components:
  schemas:
    ConnectionRequestOnME:
      properties:
        sp_host:
          type: string
        engine_name:
          type: string
    Summary:
      properties:
        sp_host:
          type: string
        engine_name:
          type: string
        dump:
          type: object
          additionalProperties:
            type: integer
    Document:
      properties:
        url:
          type: string
        title:
          type: string
        description:
          type: string
        score:
          type: number
