kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: kearch
  name: mysql-pvc
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
  selector:
    matchLabels:
      volume: sp-db-pv
