apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: kearch
  name: sp-db-00
  labels:
    engine: sp
    app: db
    volume: sp-db
spec:
  capacity:
    storage: 30Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /data/sp-db-00
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: storage
          operator: In
          values:
          - sp-db
          - sp-db-00
