apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: StatefulSet
metadata:
  namespace: kearch
  name: sp-db
  labels:
    engine: sp
    app: db
spec:
  selector:
    matchLabels:
      engine: sp
      app: db
  replicas: 1
  template:
    metadata:
      namespace: kearch
      labels:
        engine: sp
        app: db
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: sp-db-storage
          mountPath: /var/lib/mysql
        - name: config-volume
          mountPath: /etc/mysql/conf.d
      volumes:
      - name: config-volume
        configMap:
          name: sp-db
          items:
          - key: sp-db-mysql.cnf
            path: sp-db-mysql.cnf
  volumeClaimTemplates:
  - metadata:
      namespace: kearch
      name: sp-db-storage
    spec:
      selector:
        matchLabels:
          volume: sp-db
      storageClassName: local-storage
      accessModes: [ ReadWriteOnce ]
      resources:
        requests:
          storage: 12Gi
