apiVersion: v1
kind: Service
metadata:
  namespace: kearch
  name: sp-crawler-parent
  labels:
    engine: sp
    app: crawler-parent
spec:
  ports:
  - port: 10080
  selector:
    engine: sp
    app: crawler-parent
