apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kearch
  name: me-evaluator
  labels:
    engine: me
    app: evaluator
spec:
  selector:
    matchLabels:
      engine: me
      app: evaluator
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        engine: me
        app: evaluator
    spec:
      containers:
      - image: kearch/me-evaluator
        name: me-evaluator
        ports:
        - containerPort: 10080
        imagePullPolicy: Never
