apiVersion: v1
kind: Service
metadata:
  namespace: kearch
  name: me-evaluator
  labels:
    engine: me
    app: evaluator
spec:
  type: NodePort
  ports:
  - port: 10080
  selector:
    engine: me
    app: evaluator
