apiVersion: v1
kind: PersistentVolume
metadata:
  name: sp-es-master
  labels:
    volume: sp-es-master-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /data/sp-es-master-pv
  # TODO: tie this PersistentVolume to a specific node
  # nodeAffinity:
  #   required:
  #     nodeSelectorTerms:
  #     - matchExpressions:
  #       - key: kubernetes.io/hostname
  #         operator: In
  #         values:
  #         - my-node
