apiVersion: v1
kind: Service
metadata:
  name: sp-es-ingest
  labels:
    engine: sp
    app: es
    component: elasticsearch
    role: ingest
spec:
  selector:
    component: elasticsearch
    role: ingest
  ports:
  - name: http
    port: 9200
#type: LoadBalancer
