apiVersion: v1
kind: Service
metadata:
  namespace: kearch
  name: elasticsearch-data
  labels:
    engine: sp
    app: es
    component: elasticsearch
    role: data
spec:
  ports:
  - port: 9300
    name: transport
  clusterIP: None
  selector:
    component: elasticsearch
    role: data
