apiVersion: v1
kind: Service
metadata:
  name: sp-es-discovery
  labels:
    engine: sp
    component: elasticsearch
    role: master
spec:
  selector:
    component: elasticsearch
    role: master
  ports:
  - name: transport
    port: 9300
    protocol: TCP
  clusterIP: None
