apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kearch
  name: sp-crawler-child
  labels:
    engine: sp
    app: crawler-child
spec:
  selector:
    matchLabels:
      engine: sp
      app: crawler-child
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        engine: sp
        app: crawler-child
    spec:
      containers:
      - image: kearch/sp-crawler-child
        name: sp-crawler-child
        ports:
        - containerPort: 10080
        imagePullPolicy: Never
        resources:
          limits:
            memory: 1Gi
          requests:
            memory: 128Mi
