apiVersion: v1
kind: Service
metadata:
  namespace: kearch
  name: sp-crawler-child
  labels:
    engine: sp
    app: crawler-child
spec:
  type: NodePort
  ports:
  - port: 10080
  selector:
    engine: sp
    app: crawler-child
