openapi: 3.0.0
info:
  title: kearch specialist search engine query processor API
  description: kearch specialist search engine query processor API
  version: 0.1.0
servers:
  - url: '{scheme}://{sp_host}:{port}/sp/query-processor'
    variables:
      scheme:
        enum:
          - http
          - https
        default: http
      sp_host:
        default: sp-query-processor.kearch.svc.cluster.local
      port:
        default: '10080'
paths:
  /retrieve:
    get:
      parameters:
        - in: query
          name: query
          schema:
            type: string
          required: true
        - in: query
          name: max_urls
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: Search results.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Document'
components:
  schemas:
    Document:
      properties:
        url:
          type: string
        title:
          type: string
        description:
          type: string
        score:
          type: number
