apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: kearch
  name: me-db-00
  labels:
    engine: me
    app: db
    volume: me-db
spec:
  capacity:
    storage: 30Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /data/me-db-00
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: storage-me-db
          operator: Exists
