apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  namespace: kearch
  name: me-db
  labels:
    engine: me
    app: db
spec:
  selector:
    matchLabels:
      engine: me
      app: db
  strategy:
    type: Recreate
  template:
    metadata:
      namespace: kearch
      labels:
        engine: me
        app: db
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        - name: config-volume
          mountPath: /etc/mysql/conf.d
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: me-mysql-pvc
      - name: config-volume
        configMap:
          name: me-db
          items:
          - key: me-db-mysql.cnf
            path: me-db-mysql.cnf
