kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: kearch
  name: me-mysql-pvc
  labels:
    engine: me
    app: db
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
  selector:
    matchLabels:
      volume: me-db-pv
