apiVersion: v1
kind: Service
metadata:
  namespace: kearch
  name: sp-admin
  labels:
    engine: sp
    app: admin
spec:
  type: NodePort
  ports:
  - port: 10080
    nodePort: 32700
  selector:
    engine: sp
    app: admin
