apiVersion: v1
kind: Service
metadata:
  namespace: kearch
  name: me-front
spec:
  type: NodePort
  ports:
  - port: 2222
    targetPort: 2222
    protocol: TCP
  selector:
    engine: me
    app: front
  externalIPs:
  # - <set your external global ip here>
