apiVersion: v1
kind: Service
metadata:
  namespace: kearch
  name: me-gateway
  labels:
    engine: me
    app: gateway
spec:
  type: NodePort
  ports:
  - port: 10080
    nodePort: 32400
  selector:
    engine: me
    app: gateway
